### ISSUE TITLE
Choosing a collaboration tool 

### ISSUE THREAD

**Issue by rvarol** [bounswe/bounswe2017group8#10]
As we have talked in the previous meeting, we need to decide which collaboration tool to use. Two options were proposed: Slack and Trello. Please state your preference on one of the following options as a comment to this issue:

1. Slack
2. Trello
3. No need for an additional tool

You are also welcome to state your reasons for choosing the option you have or put forth another tool we can consider. But I think we should resolve this issue until the next meeting at the very latest.

**Comment by onurklngc** [comment]
Option 3 
Firstly we have similar collaboration tools and it may be harder to follow the information flow as the number of the communication tools increases.
We have telegram web for one to one code sharing.
Also, Github [Project page](https://github.com/bounswe/bounswe2017group8/projects/1) may be used for project organization purpose. It is already integrated with the issue system.

**Comment by rvarol** [comment]
I think we should use Slack.

Being able to message through different channels is a nice feature to have. Especially as we begin to work more intensively on the project, Telegram may fall ineffective and we might want separate channels to communicate through so as to make sure everyone receives messages that is related to him/her. Also, as far as I can see Slack is better in terms of code & file sharing, searching etc. compared to both Telegram and Trello. So, I think we should abandon Telegram altogether and start using Slack as our instant messaging platform.

**Comment by buraksofu** [comment]
I agree with both of you at some points.

Firstly, we shouldn't use many communication platform since it would cause confusion and would be useless, at least the ones which will be used for the same purpose. I think we should continue to use telegram for instant messaging since it's the most accesible one. For code sharing and that kind of purposes, we can give Slack a try and see how it goes.

**Comment by halilozanakgul** [comment]
I vote for Slack.  

I think having new tools to communicate might help us and during the semester if we think that we are using too much unnecessary tools we can simply stop using them.

**Comment by ozanknskl** [comment]
Whatever work means for you, Slack brings all the pieces and people you need together so you can actually get things done. Haha I think we should give it a try!

**Comment by harunzengin** [comment]
I still vote for Trello, but if you think Slack would be more practical, let's do that.

**Comment by rvarol** [comment]
We have decided to use Slack
