### ISSUE TITLE
Finalize non-functional requirements 

### ISSUE THREAD

**Issue by rvarol** [bounswe/bounswe2017group8#16]
Non-functional requirements are to be finalized in light of the customer feedback we have received today.

The deadline is 28.02.2017, 10:00 AM.

**Comment by rvarol** [comment]
I have made the following modifications in the non-functional requirements, because I think it is more clear and better defined this way.

<b>Old:</b> * <b>2.1.2.</b> Users shall be able to determine what information to share with other users in a very detailed manner.
<b>New:</b> * <b>2.1.2.</b> Users shall be able to determine what information to share with other users in a very detailed manner, such that every piece of information the user provides will have the option to be shared or not shared.</br>

<b>Old:</b> * <b>2.4.6.</b> In the event of a system failure, restart or recovery shall be possible quickly with minimum or no data corruption **(?)**
<b>New:</b> * <b>2.4.6.</b> In the event of a failure, the system will be available again with no data loss under 6 hours.<br/><br/>

I have added the following item for similar reasons.
* <b>2.3.3.1.</b> Available languages shall include English and Turkish.
<br/>

I have deleted the following item because I think it is ambiguous and I couldn't think of a better way to rewrite it.
* <b>2.2.2.</b> The website shall support mobile devices with a flexible design suitable for different screen sizes<br/><br/>

I think we should also revise the following items.
* <b>2.3.4.</b> There shall be a complete, unambiguous, structured user manual<br/>
* <b>2.4.3.</b> The website and the application shall be available upon request by the users<br/>
* <b>2.4.5.</b> The system shall have a low possibility of failure<br/>
* <b>2.4.7.</b> When under unexpectedly large workload, malicious or not, precautions shall be taken to prevent system failure and impact user access as little as possible **(?)** <br/>
* <b>2.4.8.</b> Measures shall be taken to identify and disallow unauthorized access **(?)** <br/>

**Comment by UtkuBozdogan** [comment]
- 2.1.2 new version is better, but can we actually make it this way during implementation?

- 2.4.6 looks good now, we needed some quantifiable specifications.

- 2.3.3.1 is good , it is clarified now.

- 2.2.2 I think we must mention that we support mobile platform as well but I agree it is ambiguous. Maybe something along the line "The website shall support mobile devices with an application" would work. Something general, yet not ambiguous.

- 2.3.4 Maybe we can make it a bit more specified, like it will have a glossary and mention its other contents and functions.

- 2.4.3 What I meant was it is not going to be down when people want to use it (it will have a high up-time ratio) should we elaborate on **high** ?

- 2.4.5 This one might be related to the 2.4.3 and do we need to define the term **low** here?

- 2.4.7 & 2.4.8 I am not sure if these are in valid format so I put question marks, could you please check them? @rvarol  

My edits to the non-functional part was suggestions and points, a general description of things to include with the expectation of them being edited to fit the format later on so I am fine with any change to the better.

**Comment by rvarol** [comment]
I have updated the requirements in accordance with the feedback we have received from the instructor. I have removed some items that are ambiguous for which I couldn't think of a good way to specify explicitly. It would be nice to add some specifications about how much load the web site is going to be able to handle but for that we first need to know how much we can handle and I don't have much experience about those issues. If anyone has, he/she could guide us perhaps.

I have also relaxed 2.4.6 (now 3.4.3), it should be easily doable now.

**Comment by UtkuBozdogan** [comment]
I studied the feedback now, I have come up with some solutions, could you please check them out? @rvarol 

- Old 2.4.3 "The website and the application shall be available upon request by the users"
     to be added as 3.4.4 in the following form: "The application shall have a 99 percent uptime"

- Old 2.4.4 "Updates that users make shall be available in minimum time possible" 
     to be added as 3.4.5 "Changes made by users shall be reflected on the application with an average of 1 second delay."

- Old 2.4.7 "When under unexpectedly large workload, malicious or not, precautions shall be taken to prevent system failure and impact user access as little as possible"
     to be added as 3.4.6 "The system shall operate correctly and is guaranteed to be functional up to 1000 requests per second." 

- Old 2.4.8 (this clause is also related to the 2.4.7) "Measures shall be taken to identify and disallow unauthorized access"
      following enumerated items to be considered for a future revision:
1. ddos, phishing or any other type of attack that can be made to this system
2. Users or non-users that make multiple (5 tries is appropriate in my opinion) , consecutive, unsuccessful attempts to access an account, the application may require e-mail confirmation after these attempts for a successful login. May need to discuss with customer.
