### ISSUE TITLE
API Selection

### ISSUE THREAD

**Issue by rvarol** [bounswe/bounswe2017group8#5]
In the meeting today, we have decided to research the IBM Watson API. Each member is to create an account on [BlueMix](https://console.ng.bluemix.net) and select an API under the [Services > Watson](https://console.ng.bluemix.net/catalog/?category=watson) category.

Everyone will do a research on the API he/she has chosen and contribute to the common Wiki page accordingly. Please write the API you want to study as a comment to this issue until tonight.

**Comment by rvarol** [comment]
Visual Recognition

**Comment by ozanknskl** [comment]
Tone Analyzer

**Comment by bakipin** [comment]
Personality Insights

**Comment by UtkuBozdogan** [comment]
Text to Speech

**Comment by buraksofu** [comment]
Natural Language Classifier

**Comment by onurklngc** [comment]
Conversation

**Comment by halilozanakgul** [comment]
AlchemyAPI

**Comment by harunzengin** [comment]
Language Translator

**Comment by abtasdan** [comment]
Speech to Text

**Comment by spctr** [comment]
Discovery
