### ISSUE TITLE
Requirements Draft

### ISSUE THREAD

**Issue by onurklngc** [bounswe/bounswe2017group8#9]
[Document](https://github.com/bounswe/bounswe2017group8/wiki/Requirements)

**Comment by UtkuBozdogan** [comment]
I have prepared some suggestions/additions for the draft, should I edit the draft directly or send my proposals to someone for revision?

**Comment by rvarol** [comment]
You can edit the draft directly. If you have any conflicting items with the ones already present, list them one after the other with the same item number and add some indicating message like ***CONFLICTING ITEMS*** so we can discuss over them.
